# This is just an example file that enables local testing
# It is overriden via GitOps and should not be edited here

[general]
"root_redirect_path" = "/v2"

[routes]
"v2" = "wallet/2.0.html"
"bpl" = "bpl/index.html"
"webhook" = "webhook/webhook.html"
"portal" = "portal/index.html"
"transaction" = "merchant/retail_transaction_api.html"
"midas_messaging" = "merchant/async/index.html"

"appendix" = "extras/appendix.html"
"changelog" = "extras/changelog.html"
