openapi: 3.0.0
info:
  version: 1.0.0
  title: Merchant Transaction API
  description: 'A REST endpoint for merchants to send their transactions to Bink'
paths: 
  /merchant_transactions:
    post:
      summary: "Send Merchant transactions to Bink"
      description: "Payload contains an array of transactions"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MerchantTransactions'
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericresponse400'
        '400':
          description: '**Bad request**'
components:
  schemas:
    MerchantTransactions:
      type: array
      items:
        $ref: '#/components/schemas/MerchantTransaction'
    MerchantTransaction:
      type: object
      properties: 
        transaction_id: 
          type: string
          example: 'QTZENTY0DdGOEJCQkU3'
        transaction_auth_code:
          type: string
          example: 188328
        transaction_card_first_six:
          type: number
          example: 454546
        transaction_card_last_four:
          type: number
          example: 6309
        transaction_amount: 
          type: number
          example: 23.99
        transaction_currency_code:
          type: string
          example: GBP
        merchant_identifier:
          type: string
          example: 10209723
        transaction_description: 
          type: string
          example: ''
        transaction_date: 
          type: string
          example: "2022-11-11T13:13:46"
    genericresponse400:
      type: object
      required:
        - error_message
        - error_slug
      properties:
        error_message:
          type: string
          description: 'Error message that could be displayed to a user.'
          example: 'Invalid JSON'
        error_slug:
          type: string
          description: 'Human-readable identifier that is easy to code against.'
          example: 'MALFORMED_REQUEST'

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Bink_API/MerchantTransaction/1.0.0