openapi: 3.0.0
info:
  version: 1.0.0
  title: Retailer Transaction API
  description:  "<h1>Introduction</h1>Send one or more Retailer Transactions to Bink with The Retailer Transaction API.
    <br><br>
    A Retailer Transaction object represents a customer card payment at a retailer location. <br><br> This API accepts a JSON body and provides HTTP response codes and a JSON response body.
    <h2>Authentication</h2>
    Bink uses API keys to authenticate requests. Provide your API key in every request in the X-API-KEY header. Bink will provide each retailer with an API key upon integration. 

    <h2>Errors</h2>
    Bink's API uses HTTP response codes. Codes in the 2xx range indicate success. Requests that result in errors codes have a code in the 4xx range and a JSON body containing <i>error_message</i> and <i>error_slug</i> fields. 

    <h2>Versioning</h2>
    The Retailer Transaction API is versionless, all changes will be backward-compatible. Any future changes that are backward-incompatible with result in a new API operation. 

    <h2>Idempotency</h2>
    Clients may safely retry retail transaction requests. All requests must contain a transaction identifer. You can safely resend a retail transaction provided it contains the same transaction identifier <i>(transaction_id)</i> as the original request.
    "
paths: 
  /retailers/{retailer_id}/transactions:
    post:
      security: 
        - ApiKeyAuth: [] 
      tags:
        - Retail Transactions
      summary: "Send retailer transactions to Bink"
      description: "You can send an individual or a list of transactions. Transactions must have a unique ID and contain all required parameters. To ensure optimal performance, each value should use the format specified."
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetailerTransactions'
      parameters:
        - in: path
          name: retailer_id
          description: "The unique identifier for the retailer. Bink will provide this value to you."
          required: true
          schema:
            type: string
      responses: 
        '200':
          description: OK
        '400':
          description: 'Client needs to modify the request before it can be retried.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericresponse400'
        '401':
          description: 'Client authentication failed.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericresponse401'
        '422':
          description: 'Field validation error.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericresponse422'
components:
  schemas:
    RetailerTransactions:
      type: array
      items:
        $ref: '#/components/schemas/RetailerTransaction'
    RetailerTransaction:
      type: object
      required:
        - transaction_id
        - amount
        - auth_code
        - date
        - currency_code
        - payment_card_type
      properties: 
        transaction_id: 
          type: string
          example: 'QTZENTY0DdGOEJCQkU3'
        payment_card_type:
          type: string
          description: "Specifies the payment card's type. This is usually, 'visa', 'mastercard', or 'amex', but can also have values such as 'Visa Debit' or 'Visa Credit'"
          example: 'visa'
        payment_card_first_six:
          type: string
          example: '454546'
        payment_card_last_four:
          type: string
          example: '6309'
        amount: 
          type: number
          example: 23.99
        currency_code:
          type: string
          description: "String indicating the payment currency code - usually in ISO 4217 standard"
          example: "GBP"
        auth_code:
          type: string
          description: "A number or code generated by an issuing bank for the purpose of validating a payment card whenever it is approved in the sale of a good or a service."
          example: '188328'
        date: 
          type: string
          format: date-time
          description: 'Transaction date and time in the format defined by RFC 3339, section 5.6, for example, 2023-01-30T11:14:34Z, 2023-01-30T11:14:34+00:00'
          example: "2023-01-30T11:14:34+00:00"
        merchant_identifier:
          type: string
          description: "A distinctive code that the acquirer or payment processeor assigns to retailers when they open a account. Each store or location may have its own merchant identifier. This field is required unless you provide a retailer_location_id." 
          example: '10209723'
        retailer_location_id:
          type: string
          example: "store_1"
          description: "A unique identifier, usually internal to the retailer, that identifies the store or location. This field is mandatory if you cannot provide a merchant identifier."
    genericresponse400:
      type: object
      required:
        - error_message
        - error_slug
      properties:
        error_message:
          type: string
          description: 'Error message that could be displayed to a user.'
          example: 'Invalid JSON'
        error_slug:
          type: string
          description: 'Human-readable identifier that is easy to code against.'
          example: 'MALFORMED_REQUEST'
    genericresponse401:
      type: object
      required:
        - error_message
        - error_slug
      properties:
        error_message:
          type: string
          description: 'Error message that could be displayed to a user.'
          example: 'Supplied token is invalid'
        error_slug:
          type: string
          description: 'Human-readable identifier that is easy to code against.'
          example: 'INVALID_TOKEN'
    genericresponse422:
      type: object
      required:
        - error_message
        - error_slug
        - fields
      properties:
        error_message:
          type: string
          description: 'Error message that could be displayed to a user.'
          example: 'Could not validate fields'
        error_slug:
          type: string
          description: 'Human-readable identifier that is easy to code against.'
          example: 'FIELD_VALIDATION_ERROR'
        fields:
          description: 'List of fields that failed validation.'
          type: array
          items:
            type: string
          example:
            - "expected str for dictionary value @ data['payment_card_first_six']"
            - "required key not provided @ data['auth_code']"
  securitySchemes:
    ApiKeyAuth:      
      type: apiKey
      in: header     
      name: X-API-KEY